"""acrescenta cache de sugestoes ao capitulo

Identificador desta migration: 528450832111
Vem depois de: e4e246883f15
Criada em: 2026-09-27 14:41:30.086869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores usados pelo Alembic para montar a sequência de migrations.
# "revision" é esta; "down_revision" é a anterior (None se for a primeira).
revision: str = '528450832111'
down_revision: Union[str, Sequence[str], None] = 'e4e246883f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def aplicar() -> None:
    """Aplica a mudança no banco."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capitulos', sa.Column('sugestoes_ia', sa.JSON(), nullable=True))
    op.add_column('capitulos', sa.Column('sugestoes_modelo', sa.String(length=200), nullable=True))
    op.add_column('capitulos', sa.Column('sugestoes_geradas_em', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def reverter() -> None:
    """Desfaz a mudança, voltando o banco ao estado anterior."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('capitulos', 'sugestoes_geradas_em')
    op.drop_column('capitulos', 'sugestoes_modelo')
    op.drop_column('capitulos', 'sugestoes_ia')
    # ### end Alembic commands ###


# O Alembic chama as funções pelos nomes "upgrade" e "downgrade" — são exigidos
# pela biblioteca, não escolhidos por nós. Os apelidos abaixo deixam a lógica
# com nomes em português e ainda atendem ao que o Alembic espera.
upgrade = aplicar
downgrade = reverter
