"""sugestoes persistidas em tabelas proprias

Identificador desta migration: 694c20b4e5d2
Vem depois de: 528450832111
Criada em: 2026-09-27 16:26:38.055522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Identificadores usados pelo Alembic para montar a sequência de migrations.
# "revision" é esta; "down_revision" é a anterior (None se for a primeira).
revision: str = '694c20b4e5d2'
down_revision: Union[str, Sequence[str], None] = '528450832111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def aplicar() -> None:
    """Aplica a mudança no banco.

    Ajuste feito à mão: o Alembic emitiu a restrição CHECK do campo "tipo"
    como linhas explícitas, mas ``sa.Enum`` com ``create_constraint=True`` já
    a cria junto da coluna — mesmo ajuste já feito na migration de Elemento
    (``ed7da64a05d3``), pelo mesmo motivo (duplicaria a restrição).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sugestoes_elemento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capitulo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('PERSONAGEM', 'AMBIENTE', 'OBJETO', 'CRIATURA', 'GRUPO', 'VEICULO', 'EDIFICACAO', name='tipo_elemento_sugerido', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('manter_estado_atual', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('modelo', sa.String(length=200), nullable=False),
    sa.Column('elemento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['capitulo_id'], ['capitulos.id'], name=op.f('fk_sugestoes_elemento_capitulo_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['elemento_id'], ['elementos.id'], name=op.f('fk_sugestoes_elemento_elemento_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sugestoes_elemento'))
    )
    op.create_index(op.f('ix_sugestoes_elemento_capitulo_id'), 'sugestoes_elemento', ['capitulo_id'], unique=False)
    op.create_table('sugestoes_frame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capitulo_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('horario', sa.String(length=100), nullable=True),
    sa.Column('clima', sa.String(length=100), nullable=True),
    sa.Column('humor', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=200), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['capitulo_id'], ['capitulos.id'], name=op.f('fk_sugestoes_frame_capitulo_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.id'], name=op.f('fk_sugestoes_frame_frame_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sugestoes_frame'))
    )
    op.create_index(op.f('ix_sugestoes_frame_capitulo_id'), 'sugestoes_frame', ['capitulo_id'], unique=False)
    op.create_table('sugestoes_participante',
    sa.Column('sugestao_frame_id', sa.Integer(), nullable=False),
    sa.Column('sugestao_elemento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sugestao_elemento_id'], ['sugestoes_elemento.id'], name=op.f('fk_sugestoes_participante_sugestao_elemento_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sugestao_frame_id'], ['sugestoes_frame.id'], name=op.f('fk_sugestoes_participante_sugestao_frame_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sugestao_frame_id', 'sugestao_elemento_id', name=op.f('pk_sugestoes_participante'))
    )
    op.drop_column('capitulos', 'sugestoes_ia')
    op.drop_column('capitulos', 'sugestoes_modelo')
    # ### end Alembic commands ###

    # Ajuste manual, fora do que o Alembic gerou: sugestoes_geradas_em passa a
    # significar "existem linhas em sugestoes_elemento/sugestoes_frame para
    # este capítulo" (item 3.4e), não mais "o blob antigo foi gerado". Um
    # capítulo que já tinha sugestão sob o sistema anterior ficaria com a
    # data antiga e nenhuma linha — a rota acharia que tem cache e nunca
    # chamaria a IA, devolvendo uma lista vazia para sempre. Zerar aqui é o
    # que faz a próxima chamada gerar de verdade.
    op.execute("UPDATE capitulos SET sugestoes_geradas_em = NULL")


def reverter() -> None:
    """Desfaz a mudança, voltando o banco ao estado anterior."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capitulos', sa.Column('sugestoes_modelo', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('capitulos', sa.Column('sugestoes_ia', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('sugestoes_participante')
    op.drop_index(op.f('ix_sugestoes_frame_capitulo_id'), table_name='sugestoes_frame')
    op.drop_table('sugestoes_frame')
    op.drop_index(op.f('ix_sugestoes_elemento_capitulo_id'), table_name='sugestoes_elemento')
    op.drop_table('sugestoes_elemento')
    # ### end Alembic commands ###


# O Alembic chama as funções pelos nomes "upgrade" e "downgrade" — são exigidos
# pela biblioteca, não escolhidos por nós. Os apelidos abaixo deixam a lógica
# com nomes em português e ainda atendem ao que o Alembic espera.
upgrade = aplicar
downgrade = reverter
